### ISSUE TITLE
Hostminder is causing sudo to throw a warning "sudo: unable to resolve host 'hostname': Name or service not known"

### ISSUE THREAD

**Issue by prascher** [jeremehancock/hostminder#3] opened 2023-07-05 17:41 UTC
I'm a big fan of Ubuntu CE and hostminder, but for some reason every time I run hostminder it causes sudo to throw the error `sudo: unable to resolve host _hostname_: Name or service not known`.  The issue is that for some reason it removes the hostname when I run hostminder, and as soon as I go in and manually go in and edit the line `127.0.0.1 localhost` to be `127.0.0.1 localhost _hostname_` the error goes away.

**Comment by prascher** [comment] 2023-07-05 17:51
I found the culprit it's actually the source of the lists you're using doesn't have the value set for the hostname.

**Comment by prascher** [comment] 2023-07-05 21:57
> I'm a big fan of Ubuntu CE and hostminder, but for some reason every time I run hostminder it causes sudo to throw the error `sudo: unable to resolve host _hostname_: Name or service not known`. The issue is that for some reason it removes the hostname when I run hostminder, and as soon as I go in and manually go in and edit the line `127.0.0.1 localhost` to be `127.0.0.1 localhost _hostname_` the error goes away.

I wrote the sed command that should fix it, but I'm not getting it working `sed -i "/^127.0.0.1\ localhost$/ s/$/\ $(hostname)/" /etc/hosts` is the patch code, but I can't figure out where it needs to go to make it work.

**Comment by jeremehancock** [comment] 2023-07-11 13:22
Hi @prascher 

Thank you so much for letting us know about your issues. I am sorry to hear that you are having any.

I have tried to replicate your issues, but so far I haven't been able to.

Let me ask a few questions to see if I can figure out more about what is going on.

1. Is your system running UbuntuCE or did you install the UbuntuCE Software Center to an existing Ubuntu installation?
2. What version of UbuntuCE or Ubuntu are you running?
3. Where are you seeing the error? 
4. Can you provide any screenshots?
5. Does the issue break your connection to the internet?
6. Which protection level are you trying in Host Minder?
7. Are you able to turn it off and have your default hosts file reset?

Host Minder is using the same lists that are used in the [Pi Hole](https://pi-hole.net/) project. So I don't think there are any issues with the hosts files from there since they are used on millions of machines.

I am wondering if your setup has something different than a stock UbuntuCE/Ubuntu setup that we didn't take into account for.

Thank you in advance!

**Comment by prascher** [comment] 2023-07-11 14:49
I'm running UbuntuCE 22.04, immediately after changing level to anything, no it doesn't mess up internet connection, different ones to figure out what was causing, it and even when I just disabled it and it fell back.
![Screenshot from 2023-07-11 09-44-45](https://github.com/jeremehancock/hostminder/assets/47728570/ca70b394-ffc9-4704-b9b2-f90bac93a7d9)

**Comment by jeremehancock** [comment] 2023-07-11 20:44
I think I see the issue. Are you running `hostminder` from the terminal using `sudo hostminder` ? I get the same error when I do that. You shouldn't run it with `sudo`. The Host Minder app will ask for the `sudo` password when needed.

If you run in either by selecting Host Minder from the GUI or by simply running `hostminder` from the command line without the `sudo` you shouldn't see that error. I did notice a `sed` error that I need to look into, but I don't see it causing any issues currently.

Please let me know if this resolves your issue. 

Thank you!

**Comment by jeremehancock** [comment] 2023-07-11 20:45
@prascher Oh I see what you mean now. Ok, I realize now that this is causing an issue with the use of `sudo` on any application. I will work on a fix for this. 

Thanks!!!

**Comment by jeremehancock** [comment] 2023-07-12 18:01
@prascher I have found the core issue. Basically there was a bug that caused the original hosts entries to get lost when switching between protection levels. I have pushed the fix and the new version should be available. Just run `sudo apt update && sudo apt upgrade` to get the latest version.

I would recommend that you turn off Host Minder to get back to a base hosts file. Then be sure your hostname is in the file correctly. Then update to the latest version and it should work as intended. When you enable Host Minder the original hosts entries are added to the new hosts file in a custom entries section. If you switch protection levels these custom entries will be be preserved. If you turn off Host Minder these custom entries will become your hosts file.

Please let me know if you have any questions and if this resolves your issues. 

Thanks again for reporting the issue!

**Comment by prascher** [comment] 2023-07-12 20:39
I have tested, and your fix does in fact work as it should and sudo is not throwing errors.  Thank you for the quick fix.

**Closed as completed** 2023-07-12 20:39 UTC
